pebble:
    suffix: .peb
    cache: false
spring:
    datasource:
        driver-class-name: org.postgresql.Driver
    sql:
        init:
            mode: always
    h2:
        console:
            enabled: true
    jpa:
        hibernate:
            ddl-auto: update
        defer-datasource-initialization: true
        show-sql: true
