spring:
  datasource:
    username: admin
    password: admin
    url: jdbc:postgresql://localhost:5432/kanban
    driver-class-name: org.postgresql.Driver
  liquibase:
    change-log: db/changelog/db.changelog-master.xml
